### ISSUE TITLE
Remove status "Tested" for Actions - or implement Test recipient

### ISSUE THREAD

**Issue by dw-itomig** [itomig-de/itomig-webhook-integration#11]
For the Webhook-Integration - Actions the status "tested" as no real value because there is no test recipient. So i would suggest to remove the status or add the function "send to test recipient"

**Comment by Hipska** [comment]
This field comes from the parent class `Action`, so it cannot be removed. Currently, when a web hook action is in test, then it will add "Test - " to the message of the `EventNotification` object.

Would you suggest to add a secondary URL as "test recipient"?

**Comment by larhip** [comment]
Hi @Hipska,

due to the upcoming webhook implementation by Combodo, which will be also part of the product in the future, we decided to do no more further development for this extension.

I already checked a very early beta version of the combodo implementation and there will be a way to add a secondary target URL for test mode.

As soon as there will be an official combodo version available we will describe how to migrate and archive this repository. Anyhow if you plan to use itomig-webhook-integration in the future instead of the combodo implementation, feel free to use this one as a base and do your further development within your fork.
