### ISSUE TITLE
Add Mattermost support

### ISSUE THREAD

**Issue by Hipska** [itomig-de/itomig-webhook-integration#7]
Might be a good idea to also add support for [Mattermost hooks](https://docs.mattermost.com/developer/webhooks-incoming.html).

**Comment by larhip** [comment]
Hi @Hipska,

due to the upcoming webhook implementation by Combodo, which will be also part of the product in the future, we decided to do no more further development for this extension.

As soon as there will be an official combodo version available we will describe how to migrate and archive this repository. Anyhow if you plan to use itomig-webhook-integration in the future instead of the combodo implementation, feel free to use this one as a base and do your further development within your fork.
